## Pandas

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Cache entry deserialization failed, entry ignored

In [2]:
import pandas as pd

# 1.CREATE

#### 1.1 Create series manually

In [3]:
data=[3,4,5,6,7,8]

In [4]:
pd.Series(data)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [5]:
pd.Series(data,index=['a','b','c','d','e','f'])

a    3
b    4
c    5
d    6
e    7
f    8
dtype: int64

In [6]:
a={"a":10,"b":20,"c":30,"d":40,"e":50}

In [7]:
pd.Series(a)

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### 2. Create DataFrame Manually

#### method1. From a Dictionary of Lists

In [8]:
data={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [9]:
pd.DataFrame(data)

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [10]:
df =pd.DataFrame(data)

#### method2. From a List of Dictionaries

In [11]:
data=[
    {'name':'a','age':20,'score':60,'subject':"math"},
    {'name':'b','age':30,'score':70,'subject':"physcis"},
    {'name':'c','age':40,'score':80,'subject':"chemistry"},
    {'name':'d','age':50,'score':90,'subject':"bio"}
]

In [12]:
pd.DataFrame(data)

  name  age  score    subject
0    a   20     60       math
1    b   30     70    physcis
2    c   40     80  chemistry
3    d   50     90        bio

#### 3. List Of Lists

In [13]:
data=[
    ["a",20,60,"math"],
    ["b",30,70,"physcis"]
]

In [14]:
pd.DataFrame(data,columns=['name','age','score','subject'])

  name  age  score  subject
0    a   20     60     math
1    b   30     70  physcis

# 2. Access

In [15]:
data1={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [16]:
# pd.DataFrame(data1,index=["a","b","c"])

In [17]:
df=pd.DataFrame(data1)

In [18]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [19]:
df["profession"]

0    sde
1     da
2     ds
Name: profession, dtype: object

In [20]:
df[["age","profession"]]

   age profession
0   20        sde
1   30         da
2   40         ds

In [21]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [22]:
# label-based
df.loc[2]

name          krish
age              40
profession       ds
Name: 2, dtype: object

In [23]:
df.loc[2]["name"]

'krish'

In [24]:
df.loc[1:2]

    name  age profession
1   ajay   30         da
2  krish   40         ds

In [25]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [26]:
df.index=['R01','R02','R03']

In [27]:
df

      name  age profession
R01   aman   20        sde
R02   ajay   30         da
R03  krish   40         ds

In [28]:
df.loc['R02', 'profession']

'da'

In [29]:
data2={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [30]:
df1 =pd.DataFrame(data2)

In [31]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [32]:
df1.loc[1,'profession']

'da'

In [33]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [34]:
df1[["name","profession"]]

    name profession
0   aman        sde
1   ajay         da
2  krish         ds

In [35]:
df1.iloc[0:3]

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [36]:
df1.iloc[:,0:2]

    name  age
0   aman   20
1   ajay   30
2  krish   40

In [37]:
df1.iloc[0:2]

   name  age profession
0  aman   20        sde
1  ajay   30         da

In [38]:
l=["name","age","profession"]

In [39]:
l[0:2]

['name', 'age']

In [40]:
data1={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [41]:
df=pd.DataFrame(data1)

In [42]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [43]:
df.iloc[:,0:1]

    name
0   aman
1   ajay
2  krish

In [44]:
df.iloc[:,2:3]

  profession
0        sde
1         da
2         ds

In [45]:
## ajay's age?
df.iloc[1:2,0:2]

   name  age
1  ajay   30

# 3. Edit

In [46]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [47]:
df1["name"]=["a","b","c"]

In [48]:
df1

  name  age profession
0    a   20        sde
1    b   30         da
2    c   40         ds

In [49]:
df1.loc[1, "profession"] = "ba"

In [50]:
df1

  name  age profession
0    a   20        sde
1    b   30         ba
2    c   40         ds

In [51]:
df1.loc[2]=["m",30,"da"]

In [52]:
df1

  name  age profession
0    a   20        sde
1    b   30         ba
2    m   30         da

In [53]:
df1.rename(columns={"profession":"designation"},inplace=True)

In [54]:
df1

  name  age designation
0    a   20         sde
1    b   30          ba
2    m   30          da

# 4. add

In [55]:
df1

  name  age designation
0    a   20         sde
1    b   30          ba
2    m   30          da

In [56]:
df1["work_location"]=["bangalore","mumbai","delhi"]

In [75]:
df1

  name  age designation work_location
0    a   20         sde     bangalore
1    b   30          ba        mumbai
2    m   30          da         delhi

In [88]:
df1.loc[0,"name"]="z"

In [92]:
df1.iloc[0,0]="m"

In [90]:
df1.iloc[1,1]=40

In [93]:
df1

  name  age designation work_location
0    m   20         sde     bangalore
1    b   40          ba        mumbai
2    m   30          da       chennai

## 5. Delete

In [100]:
df1

  name  age designation work_location
0    m   20         sde     bangalore
1    b   40          ba        mumbai
2    m   30          da       chennai

In [103]:
df1=df1.drop("age",axis=1)

In [104]:
df1

  name designation work_location
0    m         sde     bangalore
1    b          ba        mumbai
2    m          da       chennai

In [98]:
df1.drop(2,axis=0)

  name  age designation work_location
0    m   20         sde     bangalore
1    b   40          ba        mumbai

In [106]:
df1["designation"]=["a","b","c"]

In [107]:
df1

  name designation work_location
0    m           a     bangalore
1    b           b        mumbai
2    m           c       chennai

In [128]:
data3={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"],
}

In [129]:
df3=pd.DataFrame(data3)
df3

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [130]:
new_column={"profession":["a","b","c"]}
df4=pd.DataFrame(new_column)
df4

  profession
0          a
1          b
2          c

In [132]:
df5=pd.concat([df3,df4],axis=1)

In [153]:
df5

    name  age profession profession
0   aman   20        sde          a
1   ajay   30         da          b
2  krish   40         ds          c

In [154]:
df.columns

Index(['name', 'age', 'profession'], dtype='object')

In [151]:
df5.iloc[:, [i for i in range(len(df5.columns)) if i == 3]]

  profession
0          a
1          b
2          c

In [155]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds