## Pandas

In [3]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

# 1.CREATE

#### 1.1 Create series manually

In [5]:
data=[3,4,5,6,7,8]

In [6]:
pd.Series(data)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [7]:
pd.Series(data,index=['a','b','c','d','e','f'])

a    3
b    4
c    5
d    6
e    7
f    8
dtype: int64

In [8]:
a={"a":10,"b":20,"c":30,"d":40,"e":50}

In [9]:
pd.Series(a)

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### 2. Create DataFrame Manually

#### method1. From a Dictionary of Lists

In [10]:
data={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [11]:
pd.DataFrame(data)

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [12]:
df =pd.DataFrame(data)

#### method2. From a List of Dictionaries

In [13]:
data=[
    {'name':'a','age':20,'score':60,'subject':"math"},
    {'name':'b','age':30,'score':70,'subject':"physcis"},
    {'name':'c','age':40,'score':80,'subject':"chemistry"},
    {'name':'d','age':50,'score':90,'subject':"bio"}
]

In [14]:
pd.DataFrame(data)

  name  age  score    subject
0    a   20     60       math
1    b   30     70    physcis
2    c   40     80  chemistry
3    d   50     90        bio

#### 3. List Of Lists

In [15]:
data=[
    ["a",20,60,"math"],
    ["b",30,70,"physcis"]
]

In [16]:
pd.DataFrame(data,columns=['name','age','score','subject'])

  name  age  score  subject
0    a   20     60     math
1    b   30     70  physcis

# 2. Access

In [17]:
data1={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [ ]:
# pd.DataFrame(data1,index=["a","b","c"])

    name  age profession
a   aman   20        sde
b   ajay   30         da
c  krish   40         ds

In [34]:
df=pd.DataFrame(data1)

In [35]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [21]:
df["profession"]

0    sde
1     da
2     ds
Name: profession, dtype: str

In [22]:
df[["age","profession"]]

   age profession
0   20        sde
1   30         da
2   40         ds

In [36]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [37]:
# label-based
df.loc[2]

name          krish
age              40
profession       ds
Name: 2, dtype: object

In [38]:
df.loc[2]["name"]

'krish'

In [44]:
df.loc[1:2]

    name  age profession
1   ajay   30         da
2  krish   40         ds

In [45]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [25]:
df.index=['R01','R02','R03']

In [46]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [27]:
df.loc['R02', 'profession']

'da'

In [28]:
data2={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [29]:
df1 =pd.DataFrame(data2)

In [47]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [31]:
df1.loc[1,'profession']

'da'

In [48]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [51]:
df1[["name","profession"]]

    name profession
0   aman        sde
1   ajay         da
2  krish         ds

In [59]:
df1.iloc[0:3]

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [79]:
df1.iloc[:,0:2]

    name  age
0   aman   20
1   ajay   30
2  krish   40

In [80]:
df1.iloc[0:2]

   name  age profession
0  aman   20        sde
1  ajay   30         da

In [70]:
l=["name","age","profession"]

In [73]:
l[0:2]

['name', 'age']

# 3. Edit