## Pandas

In [329]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

In [330]:
import pandas as pd

# 1.CREATE

#### 1.1 Create series manually

In [331]:
data=[3,4,5,6,7,8]

In [332]:
pd.Series(data)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [333]:
pd.Series(data,index=['a','b','c','d','e','f'])

a    3
b    4
c    5
d    6
e    7
f    8
dtype: int64

In [334]:
a={"a":10,"b":20,"c":30,"d":40,"e":50}

In [335]:
pd.Series(a)

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### 2. Create DataFrame Manually

#### method1. From a Dictionary of Lists

In [336]:
data={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [337]:
pd.DataFrame(data)

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [338]:
df =pd.DataFrame(data)

#### method2. From a List of Dictionaries

In [339]:
data=[
    {'name':'a','age':20,'score':60,'subject':"math"},
    {'name':'b','age':30,'score':70,'subject':"physcis"},
    {'name':'c','age':40,'score':80,'subject':"chemistry"},
    {'name':'d','age':50,'score':90,'subject':"bio"}
]

In [340]:
pd.DataFrame(data)

  name  age  score    subject
0    a   20     60       math
1    b   30     70    physcis
2    c   40     80  chemistry
3    d   50     90        bio

#### 3. List Of Lists

In [341]:
data=[
    ["a",20,60,"math"],
    ["b",30,70,"physcis"]
]

In [342]:
pd.DataFrame(data,columns=['name','age','score','subject'])

  name  age  score  subject
0    a   20     60     math
1    b   30     70  physcis

# 2. Access

In [343]:
data1={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [344]:
# pd.DataFrame(data1,index=["a","b","c"])

In [345]:
df=pd.DataFrame(data1)

In [346]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [347]:
df["profession"]

0    sde
1     da
2     ds
Name: profession, dtype: str

In [348]:
df[["age","profession"]]

   age profession
0   20        sde
1   30         da
2   40         ds

In [349]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [350]:
# label-based
df.loc[2]

name          krish
age              40
profession       ds
Name: 2, dtype: object

In [351]:
df.loc[2]["name"]

'krish'

In [352]:
df.loc[1:2]

    name  age profession
1   ajay   30         da
2  krish   40         ds

In [353]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [354]:
df.index=['R01','R02','R03']

In [355]:
df

      name  age profession
R01   aman   20        sde
R02   ajay   30         da
R03  krish   40         ds

In [356]:
df.loc['R02', 'profession']

'da'

In [357]:
data2={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [358]:
df1 =pd.DataFrame(data2)

In [359]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [360]:
df1.loc[1,'profession']

'da'

In [361]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [362]:
df1[["name","profession"]]

    name profession
0   aman        sde
1   ajay         da
2  krish         ds

In [363]:
df1.iloc[0:3]

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [364]:
df1.iloc[:,0:2]

    name  age
0   aman   20
1   ajay   30
2  krish   40

In [365]:
df1.iloc[0:2]

   name  age profession
0  aman   20        sde
1  ajay   30         da

In [366]:
l=["name","age","profession"]

In [367]:
l[0:2]

['name', 'age']

In [368]:
data1={
    "name":["aman","ajay","krish"],
    "age":[20,30,40],
    "profession":["sde","da","ds"]
}

In [369]:
df=pd.DataFrame(data1)

In [370]:
df

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [371]:
df.iloc[:,0:1]

    name
0   aman
1   ajay
2  krish

In [372]:
df.iloc[:,2:3]

  profession
0        sde
1         da
2         ds

In [373]:
## ajay's age?
df.iloc[1:2,0:2]

   name  age
1  ajay   30

# 3. Edit

In [374]:
df1

    name  age profession
0   aman   20        sde
1   ajay   30         da
2  krish   40         ds

In [375]:
df1["name"]=["a","b","c"]

In [376]:
df1

  name  age profession
0    a   20        sde
1    b   30         da
2    c   40         ds

In [377]:
df1.loc[1, "profession"] = "ba"

In [378]:
df1

  name  age profession
0    a   20        sde
1    b   30         ba
2    c   40         ds

In [379]:
df1.loc[2]=["m",30,"da"]

In [380]:
df1

  name  age profession
0    a   20        sde
1    b   30         ba
2    m   30         da

In [381]:
df1.rename(columns={"profession":"designation"},inplace=True)

In [382]:
df1

  name  age designation
0    a   20         sde
1    b   30          ba
2    m   30          da

# 4. add

In [383]:
df1

  name  age designation
0    a   20         sde
1    b   30          ba
2    m   30          da

In [384]:
df1["work_location"]=["bangalore","mumbai","delhi"]

In [385]:
df1

  name  age designation work_location
0    a   20         sde     bangalore
1    b   30          ba        mumbai
2    m   30          da         delhi